#!groovy​

pipeline {
    agent { label 'cordfinance' } 
    stages { 
        stage('Pull image') {
            steps {
                script {
                    docker.withRegistry('https://terraformtest.azurecr.io/terraform-az', 'test-terraform') {
                        image = docker.image('terraformtest.azurecr.io/terraform-az')
                        image.pull()
                    }
                }
            }
        }
        stage('Terraform init') {
            steps {
                sh 'docker run -t -v /home/cfadmin/workspace/test:/opt/workspace terraformtest.azurecr.io/terraform-az sh ./terra.sh'     
            }
        }
        stage('Terraform plan') {
            steps {
                sh "export image_name"
                sh "docker run -t -v /home/cfadmin/workspace/test:/opt/workspace terraformtest.azurecr.io/terraform-az sh ./terra2.sh"
            }
        }
    }
}