#!groovy​

pipeline {
    agent { label 'cordfinance' } 

    stage('pull image'){
        docker.withRegistry('terraformtest.azurecr.io/terraform-az', 'test-terraform') {
            image = docker.image('terraform-az:latest')
            image.pull()
        }
    }
}